### ISSUE TITLE
Caching strategy

### ISSUE THREAD

**Issue by songololo** [shongololo/aiovectortiler#4]
Debating adding a caching strategy. We could use something like redis, though there may be a better way to do so using an nginx reverse proxy setup via docker containers. (Maybe a template docker-compose setup.)

Up for debate.

**Comment by jmillxyz** [comment]
What about [Tilestache](http://tilestache.org/doc/)? It's written in Python...

For the docker containers, do we also want to include some sort of simple web framework like Flask? What should the template actually do?

If we go through with having a web app, I think an example Mapbox GL JS might also be helpful, and potentially a small dataset the user could load into PostGIS. 

While we're at it, we might as well create a container for the database too... I've been meaning to learn how that would work. What do you think?

**Comment by jmillxyz** [comment]
Update: [TileStache supports Redis](http://tilestache.org/doc/#redis-cache) (among other caches) for a cache mechanism. Not sure if it's a great fit long term, as development seems to have [slowed](https://github.com/TileStache/TileStache/graphs/code-frequency).

As I understand it, the data flow would be:
PostGIS -> aiovectortiler -> TileStache -> response
