### ISSUE TITLE
Using asyncpg instead of aiopg

### ISSUE THREAD

**Issue by jmillxyz** [shongololo/aiovectortiler#6]
See [asyncpg](https://github.com/magicstack/asyncpg) -- it seems to have ~3x better performance than aiopg. I'm not sure the level of effort this would require, I'll need to see if I can try benchmarking the two.

**Comment by songololo** [comment]
Yes, worthwhile investigation. It is potentially fairly straightforward to substitute in the db_handler file. Though the aiopg implementation does use a db pool which may offset some of the speed downsides vs asyncpg.

**Comment by songololo** [comment]
Scratch that, I see it does have a [pool implementation](https://magicstack.github.io/asyncpg/current/api/index.html#connection-pool). So should be a fairly straightforward swap.

**Comment by songololo** [comment]
Completed in 83035642a8e21c35752a551f461bfd63791a042f

**Comment by songololo** [comment]
@jondelmil when switching to the asynpg version, note the new format for the DSN connection string: `postgres://user:password@host_address:port_number/database_name`

**Comment by jmillxyz** [comment]
Thanks, this works great! Did you notice any speedup in your usage?
