### ISSUE TITLE
Dynamic PostGIS recipes

### ISSUE THREAD

**Issue by jmillxyz** [shongololo/aiovectortiler#7]
Is it possible to create PostGIS queries dynamically? I imagine it would somehow need to create a new recipe.

For example, say the database contains houses. Those houses have a position and a price. How could we filter them based on price or other features, like Zillow?

**Comment by songololo** [comment]
If you include the price column in your layer sql then this should be piped through to the client, where you can then filter / style accordingly? Let me know if this is more-or-less what you had in mind.
